language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  - npm install dredd@11.2.9 nodemon mocha chai chai-http babel-register --g
  - npm run travis-test
  - npm install babel-register chai chai-http --save 
before_script:
  - dredd
env:
  -NODE_ENV=production
  -JWT_SIGNATURE=INSXSCOLABSNCKSFIRSTWSKWCCLADSJDRE234524__=654