language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
env:
  -NODE_ENV=production
  -JWT_SIGNATURE=INSXSCOLABSNCKSFIRSTWSKWCCLADSJDRE234524__=654
after_success:
  - npm run coveralls
before_install:
  - npm install mocha nodemon -g