language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  - npm install dredd@11.2.9 cross-env nodemon mocha chai chai-http babel-register --g
before_script:
  - dredd
env:
  -NODE_ENV=production
  -JWT_SIGNATURE=INSXSCOLABSNCKSFIRSTWSKWCCLADSJDRE234524__=654