FORMAT: 1A
HOST: https://wayfarer.herokuapp.com/api/v1

# wayfarer

Wayfarer is a public bus booking API
## Users Collection [/auth/users]

### Register A new User [POST /signup]

+ Response 201 (application/json)
