FORMAT: 1A
HOST: http://127.0.0.1:8001
# Wayfarer API
Official Wayfarer APIs
# Create a new user
## User [GET /api/v1/auth/signup]
+ Response 201 (application/json)
    
    + Body
            [
                {
                    "id": 1,
                    "title": "foo title",
                    "body": "bar body",
                    "author": 1
                }
            ]
